# Use an official Node.js runtime as a parent image
FROM ubuntu

RUN apt-get -y update && apt-get -y upgrade

RUN apt-get install -y nodejs

RUN apt install -y npm

# Set the working directory to /app
WORKDIR /app

# Copy package.json and package-lock.json to the working directory
COPY package*.json ./

# Install app dependencies
RUN npm install

RUN npm install -g nodemon

RUN apt-get install -y python3

RUN apt-get install -y g++

# Copy the rest of the application code to the working directory
COPY . .

# Expose port 5000
EXPOSE 5000

# Run the command to start the server
CMD [ "npm", "start" ]
